[phases.setup]
nixPkgs = ["nodejs", "pnpm"]
nixpkgsArchive = "a1f79a1770d05af18111fbbe2a3ab2c42c0f6cd0"

[phases.install]
cmds = ['pnpm install']

[phases.build]
cmds = [
    'timeout 30 pnpm run db:push --config ./drizzle.config.ts --strict=false --verbose',
    'pnpm run build'
]

[start]
cmd = 'node build'