[phases.setup]
nixPkgs = ["nodejs", "pnpm"]
nixpkgsArchive = "a1f79a1770d05af18111fbbe2a3ab2c42c0f6cd0"

[phases.install]
cmds = ['npm ci']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'node build'